//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyCovidCas
    {
        public int DailyID { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> DailyPositives { get; set; }
        public Nullable<decimal> DailyPositiveRate { get; set; }
        public int MonthlyID { get; set; }
    
        public virtual MonthlyCovidCas MonthlyCovidCas { get; set; }
    }
}
